version: "3"

vars:
  GOBIN: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT_VERSION: 'v1.64.5'

tasks:
  test:
    desc: "Run all tests"
    cmds:
      - go test -v -race ./...

  update:
    desc: "Update tests"
    cmds:
      - go run .github/update.go
      - go mod tidy

  force-update:
    desc: "Force update tests"
    aliases: [ "force_update", "fu" ]
    cmds:
      - go run .github/update.go -force
      - go mod tidy

  lint:
    desc: Run golangci-lint
    cmds:
      - |
        if [ "${OS:-}" = "Windows_NT" ]; then
          LINT="{{.GOBIN}}/golangci-lint.exe"
        
          if [ ! -f "$LINT" ]; then
            echo "golangci-lint not found. Installing..."
            mkdir -p {{.GOBIN}}
            GOBIN={{.GOBIN}} go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
          fi
        
          echo "Running golangci-lint..."
          "$LINT" run --config=.golangci.yaml --sort-results
        else 
          if [ ! -x "{{.GOBIN}}/golangci-lint" ]; then
            echo "golangci-lint not found. Installing..."
            mkdir -p {{.GOBIN}}
            GOBIN={{.GOBIN}} go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
          fi
        
          echo "Running golangci-lint..."
          {{.GOBIN}}/golangci-lint run --config=.golangci.yaml --sort-results
        fi